@baseUrl = http://localhost:3003/api

###
POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NTUwOGQ3MDQ5ZGMzZTI3NzJlMDQxYiIsImlhdCI6MTY4Mzk4MjM3NCwiZXhwIjoxNjgzOTg5NTc0fQ.YuuGSFZOP-zhkbYcGk4TV-G_Qi8fcMrcCmRBtPPly68

{
    "title": "Token testing in backend",
    "author": "VH",
    "url": "https://wwww.exampleStar.com",
    "likes": 3,
    "userId": "64552745ecd813e1ea0fd227"
}

###
GET {{baseUrl}}/blogs

###
PUT {{baseUrl}}/blogs/645f2eb5a8ff862ee90c0ed8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NTUwOGQ3MDQ5ZGMzZTI3NzJlMDQxYiIsImlhdCI6MTY4Mzk4MjM3NCwiZXhwIjoxNjgzOTg5NTc0fQ.YuuGSFZOP-zhkbYcGk4TV-G_Qi8fcMrcCmRBtPPly68

{
    "title": "some",
    "author": "author",
    "url": "urlll",
    "likes": 4,
    "userId": "64550931049dc3e2772e0420"
}


###
DELETE {{baseUrl}}/blogs/645f7f262fb2eb64d7c10ff9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NTUwOGQ3MDQ5ZGMzZTI3NzJlMDQxYiIsImlhdCI6MTY4Mzk4MjM3NCwiZXhwIjoxNjgzOTg5NTc0fQ.YuuGSFZOP-zhkbYcGk4TV-G_Qi8fcMrcCmRBtPPly68
